void getper()
{
     ModBYD[1]=Modbyd1;
     ModBYD[2]=Modbyd2;
     ModBYD[3]=Modbyd3;
     ModBYD[4]=Modbyd4;
     ModBYD[5]=Modbyd5;
     ModBYD[6]=Modbyd6;
     ModBYD[7]=Modbyd7;
     Hb[1]=Hbyd1;
     Hb[2]=Hbyd2;
     Hb[3]=Hbyd3;
     Hb[4]=Hbyd4;
     Hb[5]=Hbyd5;
     Hb[6]=Hbyd6;
     Hb[7]=Hbyd7;
     Mb[1]=Mbyd1;
     Mb[2]=Mbyd2;
     Mb[3]=Mbyd3;
     Mb[4]=Mbyd4;
     Mb[5]=Mbyd5;
     Mb[6]=Mbyd6;
     Mb[7]=Mbyd7;
}
